name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://api.github.com/repos/Aircoookie/WLED/zipball/v0.15.0-b4 -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32c3dev' >>platformio.ini
        echo 'build_flags = ${env:esp32c3dev.build_flags} -D WLED_DISABLE_OTA -D LOLIN_WIFI_FIX -D WLED_AP_SSID_UNIQUE -D WLED_DISABLE_MQTT -D WLED_DISABLE_LOXONE -D WLED_DISABLE_WEBSOCKETS -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D LEDPIN=3 -D BTNPIN=5 -D WLED_MAX_BUTTONS=2 -D WLED_MAX_USERMODS=4 -D WLED_MAX_BUSSES=8 -D DEFAULT_LED_COUNT=64 -D ABL_MILLIAMPS_DEFAULT=2000 -D DEFAULT_LED_TYPE=TYPE_WS2812_RGB -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_GRB -D WLED_MAX_LEDMAPS=64 -D MAX_LEDS=2048 -D MAX_LEDS_PER_BUS=512 -D MAX_LED_MEMORY=32000 -D CLIENT_SSID='\''"qwLed00002"'\'' -D CLIENT_PASS='\''"qwLed.00002"'\'' -D WLED_AP_SSID='\''"qwLed-AP02"'\'' -D WLED_AP_PASS='\''""'\'' -D USERMOD_AUTO_SAVE' >>platformio.ini
        
        echo 'build_unflags= -D WLED_RELEASE_NAME' >>platformio.ini
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
